#!/usr/bin/env bash

set -e

DIST="${DIST:-dist}"
TSC="${TSC:-node_modules/.bin/tsc}"

rm -rf "${DIST}"

echo 'Building CommonJS version.'
"${TSC}" \
  --project . \
  --outDir "${DIST}" \
  --module commonjs \
  --moduleResolution node

# Restructure.
rm -rf dist/test
mv dist/src/* dist/
rmdir dist/src
